apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    app: mysql-slave
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql-slave


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
  labels:
    app: mysql-slave
spec:
  selector:
    matchLabels:
      app: mysql-slave
  replicas: 2
  updateStrategy:
    type: OnDelete
  serviceName: "mysql-slave"
  template:
    metadata:
      labels:
        app: mysql-slave
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: mysql
          image: gihyodocker/tododb:latest
          imagePullPolicy: Always
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQLMASTER_HOST
              value: "mysql-master"
            - name: MYSQL_ROOT_PASSWORD
              value: "probe"
            - name: MYSQL_DATABASE
              value: "tododb"
            - name: MYSQL_USER
              value: "probe"
            - name: MYSQL_PASSWORD
              value: "probe"
            - name: MYSQL_REPL_USER
              value: "repl"
            - name: MYSQL_REPL_PASSWORD
              value: "repl"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ssd
        resources:
          requests:
            storage: 4Gi



